FROM python:3.8

#FROM ubuntu

#FROM alpine

#RUN apt-get update -y && \
    #apt-get install -y python-pip python-dev
#RUN apt-get install -y nodejs

# We copy just the requirements.txt first to leverage Docker cache
COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 5001

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]
